import { useState } from 'react'
import { Copy } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Header } from '@/components/layout/header'
import { HeaderActions } from '@/components/header-actions'
import { Main } from '@/components/layout/main'
import { Input } from '@/components/ui/input'

export function AffiliatePlan() {
  const [referralLink, setReferralLink] = useState(
    'https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  )

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(referralLink)
      // TODO: 可以在这里加一个 toast 提示
    } catch (e) {
      console.error('Copy failed', e)
    }
  }

  return (
    <>
      <Header fixed>
        <HeaderActions />
      </Header>

      <Main fluid className='flex flex-col items-center px-4 py-8 lg:py-10'>
        {/* Title & subtitle */}
        <div className='max-w-3xl text-center space-y-2 mb-6 lg:mb-8'>
          <h1 className='text-2xl font-semibold tracking-tight lg:text-3xl'>
            Not just a one–time commission, but an annual income
          </h1>
          <p className='text-sm text-muted-foreground leading-relaxed lg:text-base'>
            Get 2% of the revenue of every single deal generated by users who register through
            your affiliate link for an entire year
          </p>
        </div>

        {/* Referral link bar */}
        <div className='w-full max-w-3xl mb-8 lg:mb-10'>
          <div className='flex rounded-md border bg-background overflow-hidden h-10 text-sm shadow-sm'>
            <div className='flex items-center px-3 bg-primary text-primary-foreground font-medium whitespace-nowrap text-xs md:text-sm'>
              Your Referral Link
            </div>
            <Input
              value={referralLink}
              onChange={(e) => setReferralLink(e.target.value)}
              className='border-0 rounded-none focus-visible:ring-0 focus-visible:ring-offset-0 text-xs md:text-sm'
            />
            <Button
              type='button'
              onClick={handleCopy}
              className='rounded-none bg-primary hover:bg-primary/90 px-4 text-xs font-semibold'
            >
              <Copy className='mr-1 h-3 w-3' />
              COPY
            </Button>
          </div>
        </div>

        {/* Bottom buttons */}
        <div className='flex gap-4 lg:gap-8'>
          <Button
            variant='outline'
            className='w-48 h-10 lg:w-56 lg:h-11 text-xs lg:text-sm rounded-md border-muted-foreground/30'
          >
            Commission Records
          </Button>
          <Button
            variant='outline'
            className='w-48 h-10 lg:w-56 lg:h-11 text-xs lg:text-sm rounded-md border-muted-foreground/30'
          >
            Commission Records
          </Button>
        </div>
      </Main>
    </>
  )
}


