/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedStoreManagementRouteImport } from './routes/_authenticated/store-management'
import { Route as AuthenticatedAllProductsRouteImport } from './routes/_authenticated/all-products'
import { Route as AuthenticatedAffiliatePlanRouteImport } from './routes/_authenticated/affiliate-plan'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWinningProductsIndexRouteImport } from './routes/_authenticated/winning-products/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSupportTicketsIndexRouteImport } from './routes/_authenticated/support-tickets/index'
import { Route as AuthenticatedStoresIndexRouteImport } from './routes/_authenticated/stores/index'
import { Route as AuthenticatedStockOrdersIndexRouteImport } from './routes/_authenticated/stock-orders/index'
import { Route as AuthenticatedSourcingIndexRouteImport } from './routes/_authenticated/sourcing/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSampleOrdersIndexRouteImport } from './routes/_authenticated/sample-orders/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedRecommendProductsIndexRouteImport } from './routes/_authenticated/recommend-products/index'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes/index'
import { Route as AuthenticatedPublishedProductsIndexRouteImport } from './routes/_authenticated/published-products/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedProductConnectionsIndexRouteImport } from './routes/_authenticated/product-connections/index'
import { Route as AuthenticatedPodDesignIndexRouteImport } from './routes/_authenticated/pod-design/index'
import { Route as AuthenticatedPackagingProductsIndexRouteImport } from './routes/_authenticated/packaging-products/index'
import { Route as AuthenticatedPackagingConnectionIndexRouteImport } from './routes/_authenticated/packaging-connection/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedMyInventoryIndexRouteImport } from './routes/_authenticated/my-inventory/index'
import { Route as AuthenticatedLogisticsIndexRouteImport } from './routes/_authenticated/logistics/index'
import { Route as AuthenticatedLikedProductsIndexRouteImport } from './routes/_authenticated/liked-products/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCollectionProductsIndexRouteImport } from './routes/_authenticated/collection-products/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBrandsIndexRouteImport } from './routes/_authenticated/brands/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products/$productId'
import { Route as AuthenticatedOrdersCreateRouteImport } from './routes/_authenticated/orders/create'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedProductsProductIdPurchaseRouteImport } from './routes/_authenticated/products/$productId/purchase'
import { Route as AuthenticatedProductsProductIdDesignRouteImport } from './routes/_authenticated/products/$productId/design'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreManagementRoute =
  AuthenticatedStoreManagementRouteImport.update({
    id: '/store-management',
    path: '/store-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAllProductsRoute =
  AuthenticatedAllProductsRouteImport.update({
    id: '/all-products',
    path: '/all-products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAffiliatePlanRoute =
  AuthenticatedAffiliatePlanRouteImport.update({
    id: '/affiliate-plan',
    path: '/affiliate-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWinningProductsIndexRoute =
  AuthenticatedWinningProductsIndexRouteImport.update({
    id: '/winning-products/',
    path: '/winning-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportTicketsIndexRoute =
  AuthenticatedSupportTicketsIndexRouteImport.update({
    id: '/support-tickets/',
    path: '/support-tickets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresIndexRoute =
  AuthenticatedStoresIndexRouteImport.update({
    id: '/stores/',
    path: '/stores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockOrdersIndexRoute =
  AuthenticatedStockOrdersIndexRouteImport.update({
    id: '/stock-orders/',
    path: '/stock-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSourcingIndexRoute =
  AuthenticatedSourcingIndexRouteImport.update({
    id: '/sourcing/',
    path: '/sourcing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSampleOrdersIndexRoute =
  AuthenticatedSampleOrdersIndexRouteImport.update({
    id: '/sample-orders/',
    path: '/sample-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendProductsIndexRoute =
  AuthenticatedRecommendProductsIndexRouteImport.update({
    id: '/recommend-products/',
    path: '/recommend-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPublishedProductsIndexRoute =
  AuthenticatedPublishedProductsIndexRouteImport.update({
    id: '/published-products/',
    path: '/published-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductConnectionsIndexRoute =
  AuthenticatedProductConnectionsIndexRouteImport.update({
    id: '/product-connections/',
    path: '/product-connections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPodDesignIndexRoute =
  AuthenticatedPodDesignIndexRouteImport.update({
    id: '/pod-design/',
    path: '/pod-design/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPackagingProductsIndexRoute =
  AuthenticatedPackagingProductsIndexRouteImport.update({
    id: '/packaging-products/',
    path: '/packaging-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPackagingConnectionIndexRoute =
  AuthenticatedPackagingConnectionIndexRouteImport.update({
    id: '/packaging-connection/',
    path: '/packaging-connection/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyInventoryIndexRoute =
  AuthenticatedMyInventoryIndexRouteImport.update({
    id: '/my-inventory/',
    path: '/my-inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticsIndexRoute =
  AuthenticatedLogisticsIndexRouteImport.update({
    id: '/logistics/',
    path: '/logistics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLikedProductsIndexRoute =
  AuthenticatedLikedProductsIndexRouteImport.update({
    id: '/liked-products/',
    path: '/liked-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionProductsIndexRoute =
  AuthenticatedCollectionProductsIndexRouteImport.update({
    id: '/collection-products/',
    path: '/collection-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsIndexRoute =
  AuthenticatedBrandsIndexRouteImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersCreateRoute =
  AuthenticatedOrdersCreateRouteImport.update({
    id: '/orders/create',
    path: '/orders/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsProductIdPurchaseRoute =
  AuthenticatedProductsProductIdPurchaseRouteImport.update({
    id: '/purchase',
    path: '/purchase',
    getParentRoute: () => AuthenticatedProductsProductIdRoute,
  } as any)
const AuthenticatedProductsProductIdDesignRoute =
  AuthenticatedProductsProductIdDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedProductsProductIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/affiliate-plan': typeof AuthenticatedAffiliatePlanRoute
  '/all-products': typeof AuthenticatedAllProductsRoute
  '/store-management': typeof AuthenticatedStoreManagementRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/orders/create': typeof AuthenticatedOrdersCreateRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/collection-products': typeof AuthenticatedCollectionProductsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/liked-products': typeof AuthenticatedLikedProductsIndexRoute
  '/logistics': typeof AuthenticatedLogisticsIndexRoute
  '/my-inventory': typeof AuthenticatedMyInventoryIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/packaging-connection': typeof AuthenticatedPackagingConnectionIndexRoute
  '/packaging-products': typeof AuthenticatedPackagingProductsIndexRoute
  '/pod-design': typeof AuthenticatedPodDesignIndexRoute
  '/product-connections': typeof AuthenticatedProductConnectionsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/published-products': typeof AuthenticatedPublishedProductsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/recommend-products': typeof AuthenticatedRecommendProductsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/sample-orders': typeof AuthenticatedSampleOrdersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/sourcing': typeof AuthenticatedSourcingIndexRoute
  '/stock-orders': typeof AuthenticatedStockOrdersIndexRoute
  '/stores': typeof AuthenticatedStoresIndexRoute
  '/support-tickets': typeof AuthenticatedSupportTicketsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/winning-products': typeof AuthenticatedWinningProductsIndexRoute
  '/products/$productId/design': typeof AuthenticatedProductsProductIdDesignRoute
  '/products/$productId/purchase': typeof AuthenticatedProductsProductIdPurchaseRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/affiliate-plan': typeof AuthenticatedAffiliatePlanRoute
  '/all-products': typeof AuthenticatedAllProductsRoute
  '/store-management': typeof AuthenticatedStoreManagementRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/orders/create': typeof AuthenticatedOrdersCreateRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/collection-products': typeof AuthenticatedCollectionProductsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/liked-products': typeof AuthenticatedLikedProductsIndexRoute
  '/logistics': typeof AuthenticatedLogisticsIndexRoute
  '/my-inventory': typeof AuthenticatedMyInventoryIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/packaging-connection': typeof AuthenticatedPackagingConnectionIndexRoute
  '/packaging-products': typeof AuthenticatedPackagingProductsIndexRoute
  '/pod-design': typeof AuthenticatedPodDesignIndexRoute
  '/product-connections': typeof AuthenticatedProductConnectionsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/published-products': typeof AuthenticatedPublishedProductsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/recommend-products': typeof AuthenticatedRecommendProductsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/sample-orders': typeof AuthenticatedSampleOrdersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sourcing': typeof AuthenticatedSourcingIndexRoute
  '/stock-orders': typeof AuthenticatedStockOrdersIndexRoute
  '/stores': typeof AuthenticatedStoresIndexRoute
  '/support-tickets': typeof AuthenticatedSupportTicketsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/winning-products': typeof AuthenticatedWinningProductsIndexRoute
  '/products/$productId/design': typeof AuthenticatedProductsProductIdDesignRoute
  '/products/$productId/purchase': typeof AuthenticatedProductsProductIdPurchaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/affiliate-plan': typeof AuthenticatedAffiliatePlanRoute
  '/_authenticated/all-products': typeof AuthenticatedAllProductsRoute
  '/_authenticated/store-management': typeof AuthenticatedStoreManagementRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/orders/create': typeof AuthenticatedOrdersCreateRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRouteWithChildren
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/brands/': typeof AuthenticatedBrandsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/collection-products/': typeof AuthenticatedCollectionProductsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/liked-products/': typeof AuthenticatedLikedProductsIndexRoute
  '/_authenticated/logistics/': typeof AuthenticatedLogisticsIndexRoute
  '/_authenticated/my-inventory/': typeof AuthenticatedMyInventoryIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/packaging-connection/': typeof AuthenticatedPackagingConnectionIndexRoute
  '/_authenticated/packaging-products/': typeof AuthenticatedPackagingProductsIndexRoute
  '/_authenticated/pod-design/': typeof AuthenticatedPodDesignIndexRoute
  '/_authenticated/product-connections/': typeof AuthenticatedProductConnectionsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/published-products/': typeof AuthenticatedPublishedProductsIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/_authenticated/recommend-products/': typeof AuthenticatedRecommendProductsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/sample-orders/': typeof AuthenticatedSampleOrdersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sourcing/': typeof AuthenticatedSourcingIndexRoute
  '/_authenticated/stock-orders/': typeof AuthenticatedStockOrdersIndexRoute
  '/_authenticated/stores/': typeof AuthenticatedStoresIndexRoute
  '/_authenticated/support-tickets/': typeof AuthenticatedSupportTicketsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/winning-products/': typeof AuthenticatedWinningProductsIndexRoute
  '/_authenticated/products/$productId/design': typeof AuthenticatedProductsProductIdDesignRoute
  '/_authenticated/products/$productId/purchase': typeof AuthenticatedProductsProductIdPurchaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/affiliate-plan'
    | '/all-products'
    | '/store-management'
    | '/wallet'
    | '/'
    | '/errors/$error'
    | '/orders/create'
    | '/products/$productId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/brands'
    | '/chats'
    | '/collection-products'
    | '/help-center'
    | '/liked-products'
    | '/logistics'
    | '/my-inventory'
    | '/orders'
    | '/packaging-connection'
    | '/packaging-products'
    | '/pod-design'
    | '/product-connections'
    | '/products'
    | '/published-products'
    | '/quotes'
    | '/recommend-products'
    | '/roles'
    | '/sample-orders'
    | '/settings/'
    | '/sourcing'
    | '/stock-orders'
    | '/stores'
    | '/support-tickets'
    | '/tasks'
    | '/users'
    | '/winning-products'
    | '/products/$productId/design'
    | '/products/$productId/purchase'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/affiliate-plan'
    | '/all-products'
    | '/store-management'
    | '/wallet'
    | '/'
    | '/errors/$error'
    | '/orders/create'
    | '/products/$productId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/brands'
    | '/chats'
    | '/collection-products'
    | '/help-center'
    | '/liked-products'
    | '/logistics'
    | '/my-inventory'
    | '/orders'
    | '/packaging-connection'
    | '/packaging-products'
    | '/pod-design'
    | '/product-connections'
    | '/products'
    | '/published-products'
    | '/quotes'
    | '/recommend-products'
    | '/roles'
    | '/sample-orders'
    | '/settings'
    | '/sourcing'
    | '/stock-orders'
    | '/stores'
    | '/support-tickets'
    | '/tasks'
    | '/users'
    | '/winning-products'
    | '/products/$productId/design'
    | '/products/$productId/purchase'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/affiliate-plan'
    | '/_authenticated/all-products'
    | '/_authenticated/store-management'
    | '/_authenticated/wallet'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/orders/create'
    | '/_authenticated/products/$productId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/brands/'
    | '/_authenticated/chats/'
    | '/_authenticated/collection-products/'
    | '/_authenticated/help-center/'
    | '/_authenticated/liked-products/'
    | '/_authenticated/logistics/'
    | '/_authenticated/my-inventory/'
    | '/_authenticated/orders/'
    | '/_authenticated/packaging-connection/'
    | '/_authenticated/packaging-products/'
    | '/_authenticated/pod-design/'
    | '/_authenticated/product-connections/'
    | '/_authenticated/products/'
    | '/_authenticated/published-products/'
    | '/_authenticated/quotes/'
    | '/_authenticated/recommend-products/'
    | '/_authenticated/roles/'
    | '/_authenticated/sample-orders/'
    | '/_authenticated/settings/'
    | '/_authenticated/sourcing/'
    | '/_authenticated/stock-orders/'
    | '/_authenticated/stores/'
    | '/_authenticated/support-tickets/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/winning-products/'
    | '/_authenticated/products/$productId/design'
    | '/_authenticated/products/$productId/purchase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store-management': {
      id: '/_authenticated/store-management'
      path: '/store-management'
      fullPath: '/store-management'
      preLoaderRoute: typeof AuthenticatedStoreManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/all-products': {
      id: '/_authenticated/all-products'
      path: '/all-products'
      fullPath: '/all-products'
      preLoaderRoute: typeof AuthenticatedAllProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliate-plan': {
      id: '/_authenticated/affiliate-plan'
      path: '/affiliate-plan'
      fullPath: '/affiliate-plan'
      preLoaderRoute: typeof AuthenticatedAffiliatePlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/winning-products/': {
      id: '/_authenticated/winning-products/'
      path: '/winning-products'
      fullPath: '/winning-products'
      preLoaderRoute: typeof AuthenticatedWinningProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support-tickets/': {
      id: '/_authenticated/support-tickets/'
      path: '/support-tickets'
      fullPath: '/support-tickets'
      preLoaderRoute: typeof AuthenticatedSupportTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/': {
      id: '/_authenticated/stores/'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-orders/': {
      id: '/_authenticated/stock-orders/'
      path: '/stock-orders'
      fullPath: '/stock-orders'
      preLoaderRoute: typeof AuthenticatedStockOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sourcing/': {
      id: '/_authenticated/sourcing/'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof AuthenticatedSourcingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sample-orders/': {
      id: '/_authenticated/sample-orders/'
      path: '/sample-orders'
      fullPath: '/sample-orders'
      preLoaderRoute: typeof AuthenticatedSampleOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommend-products/': {
      id: '/_authenticated/recommend-products/'
      path: '/recommend-products'
      fullPath: '/recommend-products'
      preLoaderRoute: typeof AuthenticatedRecommendProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/published-products/': {
      id: '/_authenticated/published-products/'
      path: '/published-products'
      fullPath: '/published-products'
      preLoaderRoute: typeof AuthenticatedPublishedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-connections/': {
      id: '/_authenticated/product-connections/'
      path: '/product-connections'
      fullPath: '/product-connections'
      preLoaderRoute: typeof AuthenticatedProductConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pod-design/': {
      id: '/_authenticated/pod-design/'
      path: '/pod-design'
      fullPath: '/pod-design'
      preLoaderRoute: typeof AuthenticatedPodDesignIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packaging-products/': {
      id: '/_authenticated/packaging-products/'
      path: '/packaging-products'
      fullPath: '/packaging-products'
      preLoaderRoute: typeof AuthenticatedPackagingProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packaging-connection/': {
      id: '/_authenticated/packaging-connection/'
      path: '/packaging-connection'
      fullPath: '/packaging-connection'
      preLoaderRoute: typeof AuthenticatedPackagingConnectionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-inventory/': {
      id: '/_authenticated/my-inventory/'
      path: '/my-inventory'
      fullPath: '/my-inventory'
      preLoaderRoute: typeof AuthenticatedMyInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics/': {
      id: '/_authenticated/logistics/'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AuthenticatedLogisticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liked-products/': {
      id: '/_authenticated/liked-products/'
      path: '/liked-products'
      fullPath: '/liked-products'
      preLoaderRoute: typeof AuthenticatedLikedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection-products/': {
      id: '/_authenticated/collection-products/'
      path: '/collection-products'
      fullPath: '/collection-products'
      preLoaderRoute: typeof AuthenticatedCollectionProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/': {
      id: '/_authenticated/brands/'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/create': {
      id: '/_authenticated/orders/create'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof AuthenticatedOrdersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$productId/purchase': {
      id: '/_authenticated/products/$productId/purchase'
      path: '/purchase'
      fullPath: '/products/$productId/purchase'
      preLoaderRoute: typeof AuthenticatedProductsProductIdPurchaseRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRoute
    }
    '/_authenticated/products/$productId/design': {
      id: '/_authenticated/products/$productId/design'
      path: '/design'
      fullPath: '/products/$productId/design'
      preLoaderRoute: typeof AuthenticatedProductsProductIdDesignRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedProductsProductIdRouteChildren {
  AuthenticatedProductsProductIdDesignRoute: typeof AuthenticatedProductsProductIdDesignRoute
  AuthenticatedProductsProductIdPurchaseRoute: typeof AuthenticatedProductsProductIdPurchaseRoute
}

const AuthenticatedProductsProductIdRouteChildren: AuthenticatedProductsProductIdRouteChildren =
  {
    AuthenticatedProductsProductIdDesignRoute:
      AuthenticatedProductsProductIdDesignRoute,
    AuthenticatedProductsProductIdPurchaseRoute:
      AuthenticatedProductsProductIdPurchaseRoute,
  }

const AuthenticatedProductsProductIdRouteWithChildren =
  AuthenticatedProductsProductIdRoute._addFileChildren(
    AuthenticatedProductsProductIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAffiliatePlanRoute: typeof AuthenticatedAffiliatePlanRoute
  AuthenticatedAllProductsRoute: typeof AuthenticatedAllProductsRoute
  AuthenticatedStoreManagementRoute: typeof AuthenticatedStoreManagementRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedOrdersCreateRoute: typeof AuthenticatedOrdersCreateRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRouteWithChildren
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBrandsIndexRoute: typeof AuthenticatedBrandsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCollectionProductsIndexRoute: typeof AuthenticatedCollectionProductsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLikedProductsIndexRoute: typeof AuthenticatedLikedProductsIndexRoute
  AuthenticatedLogisticsIndexRoute: typeof AuthenticatedLogisticsIndexRoute
  AuthenticatedMyInventoryIndexRoute: typeof AuthenticatedMyInventoryIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedPackagingConnectionIndexRoute: typeof AuthenticatedPackagingConnectionIndexRoute
  AuthenticatedPackagingProductsIndexRoute: typeof AuthenticatedPackagingProductsIndexRoute
  AuthenticatedPodDesignIndexRoute: typeof AuthenticatedPodDesignIndexRoute
  AuthenticatedProductConnectionsIndexRoute: typeof AuthenticatedProductConnectionsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedPublishedProductsIndexRoute: typeof AuthenticatedPublishedProductsIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
  AuthenticatedRecommendProductsIndexRoute: typeof AuthenticatedRecommendProductsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSampleOrdersIndexRoute: typeof AuthenticatedSampleOrdersIndexRoute
  AuthenticatedSourcingIndexRoute: typeof AuthenticatedSourcingIndexRoute
  AuthenticatedStockOrdersIndexRoute: typeof AuthenticatedStockOrdersIndexRoute
  AuthenticatedStoresIndexRoute: typeof AuthenticatedStoresIndexRoute
  AuthenticatedSupportTicketsIndexRoute: typeof AuthenticatedSupportTicketsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWinningProductsIndexRoute: typeof AuthenticatedWinningProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAffiliatePlanRoute: AuthenticatedAffiliatePlanRoute,
  AuthenticatedAllProductsRoute: AuthenticatedAllProductsRoute,
  AuthenticatedStoreManagementRoute: AuthenticatedStoreManagementRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedOrdersCreateRoute: AuthenticatedOrdersCreateRoute,
  AuthenticatedProductsProductIdRoute:
    AuthenticatedProductsProductIdRouteWithChildren,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBrandsIndexRoute: AuthenticatedBrandsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCollectionProductsIndexRoute:
    AuthenticatedCollectionProductsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLikedProductsIndexRoute: AuthenticatedLikedProductsIndexRoute,
  AuthenticatedLogisticsIndexRoute: AuthenticatedLogisticsIndexRoute,
  AuthenticatedMyInventoryIndexRoute: AuthenticatedMyInventoryIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedPackagingConnectionIndexRoute:
    AuthenticatedPackagingConnectionIndexRoute,
  AuthenticatedPackagingProductsIndexRoute:
    AuthenticatedPackagingProductsIndexRoute,
  AuthenticatedPodDesignIndexRoute: AuthenticatedPodDesignIndexRoute,
  AuthenticatedProductConnectionsIndexRoute:
    AuthenticatedProductConnectionsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedPublishedProductsIndexRoute:
    AuthenticatedPublishedProductsIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
  AuthenticatedRecommendProductsIndexRoute:
    AuthenticatedRecommendProductsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSampleOrdersIndexRoute: AuthenticatedSampleOrdersIndexRoute,
  AuthenticatedSourcingIndexRoute: AuthenticatedSourcingIndexRoute,
  AuthenticatedStockOrdersIndexRoute: AuthenticatedStockOrdersIndexRoute,
  AuthenticatedStoresIndexRoute: AuthenticatedStoresIndexRoute,
  AuthenticatedSupportTicketsIndexRoute: AuthenticatedSupportTicketsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWinningProductsIndexRoute:
    AuthenticatedWinningProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
